export const moduleConfigs = {
  heroSlides: {
    title: 'Hero Slides',
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'subtitle', label: 'Subtitle' },
      { name: 'imageUrl', label: 'Image URL', required: true, type: 'image' },
      { name: 'ctaLabel', label: 'CTA Label' },
      { name: 'ctaLink', label: 'CTA Link' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['title', 'status', 'sortOrder'],
  },
  programs: {
    title: 'Programs / Courses',
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'category', label: 'Category', required: true },
      { name: 'description', label: 'Description', required: true, type: 'textarea' },
      { name: 'duration', label: 'Duration' },
      { name: 'imageUrl', label: 'Image URL', type: 'image' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['title', 'category', 'status'],
  },
  faculty: {
    title: 'Faculty / Team',
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'designation', label: 'Designation', required: true },
      { name: 'department', label: 'Department', required: true },
      { name: 'expertise', label: 'Expertise' },
      { name: 'qualification', label: 'Qualification' },
      { name: 'experience', label: 'Experience' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'linkedinUrl', label: 'LinkedIn URL' },
      { name: 'driveUrl', label: 'Drive URL' },
      { name: 'photoUrl', label: 'Photo URL', type: 'image' },
      { name: 'bio', label: 'Bio', type: 'textarea' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['name', 'department', 'designation', 'status'],
  },
  gallery: {
    title: 'Gallery / Media',
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'category', label: 'Category', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'mediaUrl', label: 'Media URL', required: true, type: 'image' },
      { name: 'mediaType', label: 'Media Type', type: 'select', options: ['image', 'video'] },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['title', 'category', 'mediaType', 'status'],
  },
  notices: {
    title: 'Notices / News / Events',
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'summary', label: 'Summary', required: true, type: 'textarea' },
      { name: 'content', label: 'Content', type: 'textarea' },
      { name: 'noticeType', label: 'Type', type: 'select', options: ['NOTICE', 'NEWS', 'EVENT'], required: true },
      { name: 'eventDate', label: 'Event Date', type: 'date' },
      { name: 'eventTime', label: 'Event Time' },
      { name: 'category', label: 'Category' },
      { name: 'tag', label: 'Tag' },
      { name: 'externalUrl', label: 'External Link' },
      { name: 'imageUrl', label: 'Image URL', type: 'image' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['title', 'noticeType', 'status'],
  },
  testimonials: {
    title: 'Testimonials',
    fields: [
      { name: 'personName', label: 'Person Name', required: true },
      { name: 'roleLabel', label: 'Role' },
      { name: 'quote', label: 'Quote', required: true, type: 'textarea' },
      { name: 'photoUrl', label: 'Photo URL', type: 'image' },
      { name: 'rating', label: 'Rating', type: 'number' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['personName', 'roleLabel', 'rating', 'status'],
  },
  transport: {
    title: 'Transport Info',
    fields: [
      { name: 'title', label: 'Route Title', required: true },
      { name: 'routeCode', label: 'Route Code' },
      { name: 'description', label: 'Description', required: true, type: 'textarea' },
      { name: 'busNo', label: 'Bus Number' },
      { name: 'driverName', label: 'Driver Name' },
      { name: 'contactPhone', label: 'Contact Phone' },
      { name: 'morningPickup', label: 'Morning Pickup' },
      { name: 'departureTime', label: 'Departure Time' },
      { name: 'stopsJson', label: 'Stops JSON', type: 'textarea' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['title', 'routeCode', 'driverName', 'status'],
  },
  uniform: {
    title: 'Uniform Info',
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'category', label: 'Category' },
      { name: 'description', label: 'Description', required: true, type: 'textarea' },
      { name: 'details', label: 'Details', type: 'textarea' },
      { name: 'priceRange', label: 'Price Range' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['title', 'category', 'priceRange', 'status'],
  },
  ebooks: {
    title: 'E-Books',
    fields: [
      { name: 'subject', label: 'Subject', required: true },
      { name: 'title', label: 'Title', required: true },
      { name: 'publisher', label: 'Publisher' },
      { name: 'linkUrl', label: 'Link URL' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['subject', 'title', 'publisher', 'status'],
  },
  administrators: {
    title: 'Administrators',
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'role', label: 'Role', required: true },
      { name: 'groupType', label: 'Group Type', type: 'select', options: ['LEADERSHIP', 'STAFF'] },
      { name: 'department', label: 'Department' },
      { name: 'qualification', label: 'Qualification' },
      { name: 'experience', label: 'Experience' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone' },
      { name: 'linkedinUrl', label: 'LinkedIn URL' },
      { name: 'photoUrl', label: 'Photo URL', type: 'image' },
      { name: 'message', label: 'Message', type: 'textarea' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['name', 'role', 'groupType', 'status'],
  },
  alumni: {
    title: 'Alumni',
    fields: [
      { name: 'name', label: 'Name', required: true },
      { name: 'photoUrl', label: 'Photo URL', type: 'image' },
      { name: 'batch', label: 'Batch' },
      { name: 'profession', label: 'Profession' },
      { name: 'company', label: 'Company' },
      { name: 'location', label: 'Location' },
      { name: 'quote', label: 'Quote', type: 'textarea' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['name', 'batch', 'profession', 'status'],
  },
  blogs: {
    title: 'Blogs',
    fields: [
      { name: 'title', label: 'Title', required: true },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { name: 'content', label: 'Content', type: 'textarea' },
      { name: 'author', label: 'Author' },
      { name: 'imageUrl', label: 'Image URL', type: 'image' },
      { name: 'externalUrl', label: 'External URL' },
      { name: 'publishedAt', label: 'Published At' },
      { name: 'sortOrder', label: 'Sort Order', type: 'number' },
      { name: 'status', label: 'Status', type: 'select', options: ['DRAFT', 'PUBLISHED'] },
    ],
    listColumns: ['title', 'author', 'publishedAt', 'status'],
  },
};

export const sidebarLinks = [
  { to: '/admin', label: 'Overview' },
  { to: '/admin/site-settings', label: 'Site Settings' },
  { to: '/admin/about', label: 'About Content' },
  { to: '/admin/admissions', label: 'Admissions Info' },
  { to: '/admin/modules/heroSlides', label: 'Hero Slides' },
  { to: '/admin/modules/programs', label: 'Programs' },
  { to: '/admin/modules/faculty', label: 'Faculty' },
  { to: '/admin/modules/gallery', label: 'Gallery' },
  { to: '/admin/modules/notices', label: 'Notices/News/Events' },
  { to: '/admin/modules/testimonials', label: 'Testimonials' },
  { to: '/admin/modules/transport', label: 'Transport' },
  { to: '/admin/modules/uniform', label: 'Uniform' },
  { to: '/admin/modules/ebooks', label: 'E-Books' },
  { to: '/admin/modules/administrators', label: 'Administrators' },
  { to: '/admin/modules/alumni', label: 'Alumni' },
  { to: '/admin/modules/blogs', label: 'Blogs' },
];
